name: 03 - Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
              description: Whether to execute cache step
              type: boolean
              default: true
            node-version:
                description: Node version
                type: choice
                options:
                  - 18.x
                  - 20.x
                  - 21.x
                default: 20.x
jobs:
  install-deps:
    runs-on: unbuntu-latest
    # defaults:                   # Set defaults at job level
    #     run:                    # Set default working directory for all run steps
    #       working-directory: .github/workflows/13-caching
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cache dependencies
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('.gihub/workflows/13-caching') }}" >> "$GITHUB_OUTPUT"
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: .github/workflows/13-caching                  # This would be the full path directory of nodes_module (files/folder) to cache
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}       # This would be the package-lock.json or similar file unique identifier for cached content
      # 2. Install dependencies
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  lint-test:
    runs-on: ubuntu-latest
    needs: install-deps
    # defaults:                 # Set defaults at job level
    #     run:                  # Set default working directory for all run steps
    #         working-directory: .github/workflows/13-caching
    steps:
      # 1. Check out code
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: .github/workflows/13-caching                      # This would be the full path directory to the node_modules folder
          key: ${{ needs.install-deps.outputs.deps-cache-key }}   # This would be the package-lock.json file for the react app
          restore-keys: |
            deps-node-modules-               # This is a prefix for the cache key to restore the cache if the exact key is not found
      # 2. Install dependencies
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      # 3. Unit testing, building
      - name: Testing
        run: npm run test
      - name: Linting
        run: echo "Linting..."
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    # defaults:                 # Set defaults at job level
    #     run:                  # Set default working directory for all run steps
    #         working-directory: .github/workflows/13-caching
    steps:
      # 1. Check out code
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: .github/workflows/13-caching                                      # This would be the full path directory to the node_modules folder
          key: ${{ needs.install-deps.outputs.deps-cache-key }}   # This would be the package-lock.json file for the react app
      # 2. Install dependencies
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      # 3. Building
      - name: Building
        run: npm run build