name: 15 - Matrices
on:
    workflow_dispatch:
jobs:
    backwards-compatibility:
        runs-on: ${{ matrix.os}}-${{ matrix.node-version }}
        strategy:
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest             # Minutes x 1
                    - windows-latest            # Minutes x 2
                    # - macos-latest            # Minutes x 10
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Perform tests
              run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"