name: 15 - Matrices
on:
    workflow_dispatch:
jobs:
    backwards-compatibility:
        runs-on: ${{ matrix.os}}-${{ matrix.node-version }}
        strategy:
            fail-fast: false                    # Set at strategy level; if one job fails, the rest will continue to run
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest             # Minutes x 1
                    - windows-latest            # Minutes x 2
                    # - macos-latest            # Minutes x 10
                include:                        # Applies only to specified options
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Perform tests
              run: |
                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
                sleep 10
            - name: Upload test results
              run: echo "Uploading test results"
    include-example:
      name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          color: [red, green]
          shape: [cirlce, square]
          size: [small, large]
          include:                        # Precedence depends on order; latest entry in array overrides previous ones
            - opacity: 50                 # Added to every entry of matrix; can be added to original values without overriding them
            - color: red                  # Everything with red has opacity of 75
              opacity: 75
            - shape: circle               # Everything with circle has opacity of 100
              opacity: 100
            - color: red                  # Adds entry to matrix at run; cannot be added to orginal values without overriding them
              shape: triangle
            - color: green
              shape: circle
              size: medium
          exclude:                        # Processed before include block
            - color: green                # Partial matches are valid
              shape: circle
      steps:
        - name: Dummy step
          run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"