name: 19 - Managing Concurrency
on:
  workflow_dispatch:

concurrency:          # Good practice to use different group names for each work flow to avoid possible canceling jobs in other workflows
  group: ${{ github.workflow }}-${{ github.ref }}   # Current workflow and branch names

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Ping URL
        id: ping-url
        run: ping https://www.google.com -c 20 -i 5
        # with:
        #   url: https://www.google.com
        #   max_trials: 20
        #   delay: 5