name: 19 - 2 - Managing Concurrency
on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: 'IP to ping'
        required: true
        default: 8.8.8.8
        type: string
      max_trails:
        description: 'Max number of pings'
        required: true
        default: 20
        type: number
      delay:
        description: 'Delay between pings'
        required: true
        default: 5
        type: number

jobs:
  ping:
    runs-on: ubuntu-latest
    concurrency:                # At the job level, if workflow is run multiple times, follow-on jobs will wait for this one to finish
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v7
      - name: Ping URL
        id: ping-url
        run: ping -c ${{ inputs.max_trails}} -i ${{ inputs.delay }} ${{ inputs.ip_address }}
  ping-without-concurrency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Ping URL
        id: ping-url
        run: ping -c ${{ inputs.max_trails}} -i ${{ inputs.delay }} ${{ inputs.ip_address }}